### ISSUE TITLE
minor: tutorial is not viewable directly on github

### ISSUE THREAD

**Issue by ctb** [jakobnissen/vamb#6]
there's no simple way to look at the tutorial on github because the github web site won't render HTML for the viewer; you have to clone the repo and open tutorial.html on your local machine.

since it seems like it comes from a Jupyter Notebook, the raw .ipynb file could checked in; github renders those!

alternatively, a markdown version of the notebook could be created (Jupyter can export these) and checked in as well!

**Comment by jakobnissen** [comment]
Good point! I'll add the `.ipynb` file to the `doc/` directory.

**Comment by ctb** [comment]
thank you!
